<?php

namespace App\Http\Controllers;

use App\Models\Affiliate;
use App\Models\AffiliateSale;
use App\Models\AffiliateWithdrawal;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

class AffiliateController extends Controller
{
    public function index()
    {
        $user = Auth::user();
        $affiliate = $user->affiliate;

        // If user has never registered as affiliate
        if (!$affiliate) {
            return view('affiliates.register');
        }

        // If affiliate is pending approval
        if ($affiliate->status === 'pending') {
            return view('affiliates.pending');
        }

        // If affiliate is rejected
        if ($affiliate->status === 'rejected') {
            return view('affiliates.rejected', compact('affiliate'));
        }

        // If affiliate is approved, show dashboard
        return $this->dashboard();
    }

    public function register(Request $request)
    {
        $validated = $request->validate([
            'ktp_name' => 'required|string|max:255',
            'ktp_photo' => 'required|image|max:200',
            'bank_account_name' => 'required|string|max:255',
            'bank_name' => 'required|string|max:255',
            'bank_account_number' => 'required|string|max:50',
            'bank_book_photo' => 'required|image|max:200',
        ]);

        // Validate that KTP name and bank account name match
        if ($validated['ktp_name'] !== $validated['bank_account_name']) {
            return back()->withErrors([
                'bank_account_name' => 'Nama di KTP dan Buku Rekening harus sama.'
            ])->withInput();
        }

        // Upload files
        $ktpPath = $request->file('ktp_photo')->store('affiliates/ktp', 'public');
        $bankBookPath = $request->file('bank_book_photo')->store('affiliates/bank', 'public');

        // Create affiliate record (referral_code will be auto-generated by model)
        Affiliate::create([
            'user_id' => Auth::id(),
            'ktp_name' => $validated['ktp_name'],
            'ktp_photo' => $ktpPath,
            'bank_account_name' => $validated['bank_account_name'],
            'bank_name' => $validated['bank_name'],
            'bank_account_number' => $validated['bank_account_number'],
            'bank_book_photo' => $bankBookPath,
            'status' => 'pending',
        ]);

        return redirect()->route('affiliates.index')->with('success', 'Pendaftaran berhasil! Dokumen Anda sedang direview.');
    }

    public function dashboard()
    {
        $affiliate = Auth::user()->affiliate;

        if (!$affiliate || $affiliate->status !== 'approved') {
            return redirect()->route('affiliates.index');
        }

        // Get current month and year earnings
        $currentMonth = now()->month;
        $currentYear = now()->year;

        $monthlyEarnings = AffiliateSale::where('affiliate_id', $affiliate->id)
            ->whereMonth('created_at', $currentMonth)
            ->whereYear('created_at', $currentYear)
            ->sum('commission_amount');

        $yearlyEarnings = AffiliateSale::where('affiliate_id', $affiliate->id)
            ->whereYear('created_at', $currentYear)
            ->sum('commission_amount');

        $totalSales = AffiliateSale::where('affiliate_id', $affiliate->id)->count();

        // Get withdrawals
        $withdrawals = AffiliateWithdrawal::where('affiliate_id', $affiliate->id)
            ->latest()
            ->get();

        // Get recent sales
        $recentSales = AffiliateSale::where('affiliate_id', $affiliate->id)
            ->with('registration.training')
            ->latest()
            ->take(10)
            ->get();

        return view('affiliates.dashboard', compact(
            'affiliate',
            'monthlyEarnings',
            'yearlyEarnings',
            'totalSales',
            'withdrawals',
            'recentSales'
        ));
    }

    public function requestWithdrawal(Request $request)
    {
        $minWithdrawal = config('affiliate.min_withdrawal', 100000);
        $taxRate = config('affiliate.tax_rate', 0.11);
        $platformFeeRate = config('affiliate.platform_fee_rate', 0.05);

        $validated = $request->validate([
            'amount' => 'required|numeric|min:' . $minWithdrawal,
        ]);

        $affiliate = Auth::user()->affiliate;

        // Check if affiliate has enough balance (Points System)
        $availablePoints = $affiliate->total_points - $affiliate->withdrawn_points - $affiliate->pending_points;

        if ($validated['amount'] > $availablePoints) {
            return back()->withErrors(['amount' => 'Saldo poin tidak mencukupi.']);
        }

        // Calculate deductions
        $taxAmount = $validated['amount'] * $taxRate;
        $platformFee = $validated['amount'] * $platformFeeRate;
        $netAmount = $validated['amount'] - $taxAmount - $platformFee;

        // Create withdrawal request
        AffiliateWithdrawal::create([
            'affiliate_id' => $affiliate->id,
            'amount' => $validated['amount'],
            'tax_amount' => $taxAmount,
            'platform_fee' => $platformFee,
            'net_amount' => $netAmount,
            'status' => 'requested',
        ]);

        // Update pending points
        $affiliate->increment('pending_points', $validated['amount']);

        return back()->with('success', 'Permintaan pencairan berhasil diajukan.');
    }

    public function sales(Request $request)
    {
        $affiliate = Auth::user()->affiliate;

        if (!$affiliate || $affiliate->status !== 'approved') {
            return redirect()->route('affiliates.index');
        }

        // Query sales with filters
        $query = AffiliateSale::where('affiliate_id', $affiliate->id)
            ->with(['registration.training', 'registration']);

        // Filter by date range
        if ($request->filled('start_date')) {
            $query->whereDate('created_at', '>=', $request->start_date);
        }
        if ($request->filled('end_date')) {
            $query->whereDate('created_at', '<=', $request->end_date);
        }

        // Filter by status
        if ($request->filled('status')) {
            $query->where('status', $request->status);
        }

        // Search by training name or customer name
        if ($request->filled('search')) {
            $search = $request->search;
            $query->whereHas('registration', function ($q) use ($search) {
                $q->where('name', 'like', "%{$search}%")
                    ->orWhereHas('training', function ($q2) use ($search) {
                        $q2->where('title', 'like', "%{$search}%");
                    });
            });
        }

        $sales = $query->latest()->paginate(20)->withQueryString();

        return view('affiliates.sales', compact('affiliate', 'sales'));
    }

    public function points(Request $request)
    {
        $affiliate = Auth::user()->affiliate;

        if (!$affiliate || $affiliate->status !== 'approved') {
            return redirect()->route('affiliates.index');
        }

        // 1. Get Sales (Points In)
        $salesQuery = AffiliateSale::where('affiliate_id', $affiliate->id)
            ->with(['registration.training']);

        if ($request->filled('start_date')) {
            $salesQuery->whereDate('created_at', '>=', $request->start_date);
        }
        if ($request->filled('end_date')) {
            $salesQuery->whereDate('created_at', '<=', $request->end_date);
        }

        $sales = $salesQuery->get()->map(function ($sale) {
            return [
                'id' => 'sale_' . $sale->id,
                'created_at' => $sale->created_at,
                'type' => 'in', // Masuk
                'description' => 'Komisi: ' . ($sale->registration->training->title ?? 'Training'),
                'amount' => $sale->commission_amount,
                'status' => $sale->status,
                'raw_status' => $sale->status
            ];
        });

        // 2. Get Withdrawals (Points Out)
        $withdrawalsQuery = AffiliateWithdrawal::where('affiliate_id', $affiliate->id);

        if ($request->filled('start_date')) {
            $withdrawalsQuery->whereDate('created_at', '>=', $request->start_date);
        }
        if ($request->filled('end_date')) {
            $withdrawalsQuery->whereDate('created_at', '<=', $request->end_date);
        }

        $withdrawals = $withdrawalsQuery->get()->map(function ($withdrawal) {
            return [
                'id' => 'wd_' . $withdrawal->id,
                'created_at' => $withdrawal->created_at,
                'type' => 'out', // Keluar
                'description' => 'Pencairan Poin',
                'amount' => $withdrawal->amount,
                'status' => $withdrawal->status,
                'raw_status' => $withdrawal->status
            ];
        });

        // 3. Merge and Sort
        $history = $sales->concat($withdrawals)->sortByDesc('created_at');

        // 4. Manual Pagination
        $perPage = 20;
        $page = $request->input('page', 1);
        $total = $history->count();
        $items = $history->slice(($page - 1) * $perPage, $perPage)->values();

        $paginatedHistory = new \Illuminate\Pagination\LengthAwarePaginator(
            $items,
            $total,
            $perPage,
            $page,
            ['path' => $request->url(), 'query' => $request->query()]
        );

        return view('affiliates.points', compact('affiliate', 'paginatedHistory'));
    }
}
